<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>comment</key>
	<string>This is just a basic wrapper around source.yaml to give Extended Perl YAML files a custom Build System.</string>
	<key>fileTypes</key>
	<array>
		<string>yaml.ep</string>
	</array>
	<key>name</key>
	<string>ModernPerl Extended YAML</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string></string>
			<key>end</key>
			<string>(?!)</string>
			<key>name</key>
			<string>source.yaml</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.yaml</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.ep</string>
	<key>uuid</key>
	<string>0f6b62ca-5771-488f-9965-9ced2ac834d7</string>
</dict>
</plist>
